# Generated by Django 6.0.4 on 2026-05-06 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('numero_serie', models.CharField(max_length=255, unique=True, verbose_name='Numéro de série')),
                ('etat', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_PANNE', 'En panne'), ('EN_MAINTENANCE', 'En maintenance')], default='DISPONIBLE', max_length=20, verbose_name='État')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('salle', models.CharField(max_length=120, verbose_name='Salle')),
                ('niveau_cible', models.CharField(max_length=100, verbose_name='Niveau cible')),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ateliers_tutores', to=settings.AUTH_USER_MODEL, verbose_name='Tuteur')),
            ],
            options={
                'verbose_name': 'Atelier',
                'verbose_name_plural': 'Ateliers',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours'), ('RESOLU', 'Résolu')], default='OUVERT', max_length=20, verbose_name='Statut')),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='logistics.equipment', verbose_name='Équipement')),
                ('ouvert_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_ouverts', to=settings.AUTH_USER_MODEL, verbose_name='Ouvert par')),
                ('atelier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='logistics.workshop', verbose_name='Atelier')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-id'],
            },
        ),
    ]
