# Generated by Django 6.0.4 on 2026-05-26 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('RETURNED', 'Retournée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('atelier_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_materiel', to='logistics.workshop', verbose_name='Atelier cible')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_materiel', to='logistics.equipment', verbose_name='Équipement')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_materiel', to=settings.AUTH_USER_MODEL, verbose_name='Formateur')),
            ],
            options={
                'verbose_name': 'Demande de matériel',
                'verbose_name_plural': 'Demandes de matériel',
                'ordering': ['-date_creation'],
            },
        ),
    ]
