# Generated by Django 4.2.30 on 2026-06-21 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logistics", "0002_demandemateriel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demandemateriel",
            name="formateur",
        ),
        migrations.AddField(
            model_name="demandemateriel",
            name="demandeur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demandes_materiel",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Demandeur",
            ),
        ),
        migrations.AddField(
            model_name="demandemateriel",
            name="destinataire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demandes_recues",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Destinataire",
            ),
        ),
    ]
