# Generated by Django 6.0.4 on 2026-06-20 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_demandemateriel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='numero_serie',
        ),
        migrations.AddField(
            model_name='equipment',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='reference',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Référence'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=5, verbose_name="Seuil d'alerte"),
        ),
        migrations.AddField(
            model_name='equipment',
            name='stock_disponible',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock disponible'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='stock_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock total'),
        ),
    ]
