# Generated by Django 4.2.30 on 2026-06-21 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logistics", "0003_remove_demandemateriel_formateur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandemateriel",
            name="demandeur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demandes_materiel",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Demandeur",
            ),
        ),
    ]
