# Generated by Django 4.2.30 on 2026-08-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0004_workshop_createur_workshop_est_annule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["-date_creation", "-id"],
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Date de création"
            ),
        ),
    ]
