# Generated by Django 4.2.30 on 2026-06-17 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_action", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SUPPRESSION_COURS", "Suppression de cours"),
                            ("SUPPRESSION_CHAPITRE", "Suppression de chapitre"),
                            ("SUPPRESSION_DEVOIR", "Suppression de devoir"),
                            ("NOTATION_SOUMISSION", "Notation de soumission"),
                            ("CREATION_COURS", "Création de cours"),
                            ("MODIFICATION_COURS", "Modification de cours"),
                            ("MODIFICATION_ROLE", "Modification de rôle"),
                            ("MODIFICATION_STATUT", "Modification de statut de compte"),
                            ("ACTIVATION_ELEVE", "Activation d'élève"),
                        ],
                        max_length=50,
                    ),
                ),
                ("type_objet", models.CharField(max_length=100)),
                ("id_objet", models.CharField(blank=True, max_length=255, null=True)),
                ("representation", models.TextField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, null=True)),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_action"],
            },
        ),
    ]
