# Generated by Django 6.0.6 on 2026-06-13 17:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du cours')),
                ('description', models.TextField(verbose_name='Description')),
                ('resume', models.TextField(blank=True, help_text='Résumé affiché dans les listes', verbose_name='Résumé court')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='accounts.niveau', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du chapitre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(help_text='Numéro de position dans le cours', verbose_name="Ordre d'affichage")),
                ('url_video', models.URLField(blank=True, help_text='Lien vers la vidéo YouTube', validators=[django.core.validators.URLValidator()], verbose_name='URL vidéo YouTube')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='apprentissage.cours', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ['cours', 'ordre'],
                'unique_together': {('cours', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du document')),
                ('type_document', models.CharField(choices=[('TP', 'TP (Travaux Pratiques)'), ('ATELIER', 'Atelier'), ('PROJET', 'Projet'), ('QCM', 'QCM (Questionnaire)'), ('COURS', 'Cours'), ('RESSOURCE', 'Ressource')], default='RESSOURCE', max_length=20, verbose_name='Type de document')),
                ('fichier_pdf', models.FileField(help_text='PDF à télécharger ou analyser', upload_to='documents/%Y/%m/', verbose_name='Fichier PDF')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('contenu_extrait', models.TextField(blank=True, help_text='Rempli automatiquement lors du téléchargement', verbose_name='Contenu extrait du PDF')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='apprentissage.chapitre', verbose_name='Chapitre')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['chapitre', 'type_document', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ChapitreComplete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_completion', models.DateTimeField(auto_now=True, verbose_name='Date de completion')),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='apprentissage.chapitre', verbose_name='Chapitre')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres_completes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Chapitre terminé',
                'verbose_name_plural': 'Chapitres terminés',
                'ordering': ['-date_completion'],
                'unique_together': {('etudiant', 'chapitre')},
            },
        ),
        migrations.CreateModel(
            name='ChapitreVisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_visite', models.DateTimeField(auto_now=True, verbose_name='Date de visite')),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='apprentissage.chapitre', verbose_name='Chapitre')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres_visites', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Visite de chapitre',
                'verbose_name_plural': 'Visites de chapitres',
                'ordering': ['-date_visite'],
                'unique_together': {('etudiant', 'chapitre')},
            },
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_derniere_consultation', models.DateTimeField(auto_now=True, verbose_name='Date de dernière consultation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('chapitres_valides', models.ManyToManyField(blank=True, related_name='progressions', to='apprentissage.chapitre', verbose_name='Chapitres validés')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='apprentissage.cours', verbose_name='Cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Progression',
                'verbose_name_plural': 'Progressions',
                'ordering': ['-date_derniere_consultation'],
                'unique_together': {('etudiant', 'cours')},
            },
        ),
    ]
