# Generated by Django 6.0.4 on 2026-05-26 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('apprentissage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='accounts.niveau', verbose_name='Niveau'),
        ),
    ]
