# Generated by Django 4.2.30 on 2026-06-17 15:12

import apprentissage.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apprentissage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Devoir",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                ("consigne", models.TextField(verbose_name="Consigne")),
                (
                    "fichier_consigne",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="devoirs/consignes/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                ]
                            ),
                            apprentissage.models.validate_file_size,
                        ],
                        verbose_name="Fichier consigne (facultatif)",
                    ),
                ),
                (
                    "date_limite",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date limite de rendu"
                    ),
                ),
                (
                    "note_max",
                    models.PositiveSmallIntegerField(
                        default=20, verbose_name="Note maximale"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "chapitre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devoirs",
                        to="apprentissage.chapitre",
                        verbose_name="Chapitre",
                    ),
                ),
                (
                    "createur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devoirs_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devoir",
                "verbose_name_plural": "Devoirs",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Soumission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="devoirs/soumissions/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                ]
                            ),
                            apprentissage.models.validate_file_size,
                        ],
                        verbose_name="Fichier soumis",
                    ),
                ),
                (
                    "commentaire_eleve",
                    models.TextField(blank=True, verbose_name="Commentaire de l'élève"),
                ),
                (
                    "date_soumission",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de soumission"
                    ),
                ),
                (
                    "note",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Note obtenue",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="Feedback du formateur"),
                ),
                (
                    "date_correction",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de correction"
                    ),
                ),
                (
                    "corrige_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="soumissions_corrigees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Corrigé par",
                    ),
                ),
                (
                    "devoir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soumissions",
                        to="apprentissage.devoir",
                        verbose_name="Devoir",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soumissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Étudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soumission",
                "verbose_name_plural": "Soumissions",
                "ordering": ["-date_soumission"],
                "unique_together": {("devoir", "etudiant")},
            },
        ),
    ]
