# Generated by Django 6.0.4 on 2026-05-08 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentissage', '0002_cours_createur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_derniere_consultation', models.DateTimeField(auto_now=True, verbose_name='Date de dernière consultation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('chapitres_valides', models.ManyToManyField(blank=True, related_name='progressions', to='apprentissage.chapitre', verbose_name='Chapitres validés')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='apprentissage.cours', verbose_name='Cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Progression',
                'verbose_name_plural': 'Progressions',
                'ordering': ['-date_derniere_consultation'],
                'unique_together': {('etudiant', 'cours')},
            },
        ),
    ]
