# Generated by Django 4.2.30 on 2026-06-18 12:21

import apprentissage.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apprentissage", "0005_evenement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="fichier_pdf",
            field=models.FileField(
                help_text="PDF à télécharger ou analyser",
                upload_to="documents/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    apprentissage.models.validate_file_size,
                ],
                verbose_name="Fichier PDF",
            ),
        ),
    ]
