# Generated by Django 6.0.4 on 2026-06-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentissage', '0006_alter_document_fichier_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='cours_covers/', verbose_name='Image de couverture'),
        ),
    ]
