# Generated by Django 5.2.15 on 2026-07-14 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentissage', '0007_cours_image_couverture'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='fichier_video',
            field=models.FileField(blank=True, help_text='Vidéo MP4 pour le fonctionnement hors-ligne sans Internet', null=True, upload_to='videos/chapitres/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='Vidéo locale (Offline)'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='url_video',
            field=models.URLField(blank=True, help_text='Lien vers la vidéo YouTube (Mode Cloud)', validators=[django.core.validators.URLValidator()], verbose_name='URL vidéo YouTube'),
        ),
    ]
