# Generated by Django 4.2.30 on 2026-07-19 17:36

import apprentissage.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apprentissage", "0007_cours_image_couverture"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapitre",
            name="video_fichier",
            field=models.FileField(
                blank=True,
                help_text="Utilisée automatiquement à la place du lien YouTube quand l'élève n'a pas de connexion internet.",
                null=True,
                upload_to="videos/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4"]
                    ),
                    apprentissage.models.validate_video_file_size,
                ],
                verbose_name="Vidéo hors-ligne (MP4)",
            ),
        ),
    ]
