# Generated by Django 4.2.30 on 2026-06-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apprentissage", "0007_cours_image_couverture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="type_document",
            field=models.CharField(
                choices=[
                    ("TP", "TP (Travaux Pratiques)"),
                    ("ATELIER", "Atelier"),
                    ("PROJET", "Projet"),
                    ("COURS", "Cours"),
                    ("RESSOURCE", "Ressource"),
                ],
                default="RESSOURCE",
                max_length=20,
                verbose_name="Type de document",
            ),
        ),
    ]
