# Generated by Django 5.2.15 on 2026-07-21 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentissage', '0008_chapitre_video_fichier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'En cours'), ('SUCCESS', 'Terminé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('fichier_zip', models.FileField(blank=True, null=True, upload_to='exports/cours/%Y/%m/', verbose_name='Fichier ZIP')),
                ('erreur', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='apprentissage.cours', verbose_name='Cours')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Formateur')),
            ],
            options={
                'verbose_name': "Tâche d'export",
                'verbose_name_plural': "Tâches d'export",
                'ordering': ['-date_creation'],
            },
        ),
    ]
