# Generated by Django 5.2.16 on 2026-08-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentissage', '0010_importjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='is_hls_ready',
            field=models.BooleanField(default=False, verbose_name='HLS Prêt'),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='video_hls_url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Chemin Playlist HLS'),
        ),
        migrations.DeleteModel(
            name='ImportJob',
        ),
    ]
