# Generated by Django 5.2.16 on 2026-08-05 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentissage', '0011_chapitre_is_hls_ready_chapitre_video_hls_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EXTRACTION', 'Extraction du ZIP'), ('SAUVEGARDE_BDD', 'Sauvegarde en base de données'), ('INDEXATION_IA', "Indexation pour l'IA"), ('TERMINE', 'Terminé'), ('FAILED', 'Échoué')], default='EN_ATTENTE', max_length=30)),
                ('titre_cours', models.CharField(blank=True, max_length=255, null=True)),
                ('erreur', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Formateur')),
            ],
            options={
                'verbose_name': "Tâche d'import",
                'verbose_name_plural': "Tâches d'import",
                'ordering': ['-date_creation'],
            },
        ),
    ]
