# Generated by Django 4.2.30 on 2026-08-28 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apprentissage", "0012_importjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="SatelliteUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "logical_name",
                    models.CharField(max_length=255, verbose_name="Nom du fichier"),
                ),
                (
                    "file_hash",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Empreinte SHA-256",
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(default=0, verbose_name="Taille (octets)"),
                ),
                (
                    "cycle_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Cycle satellite"
                    ),
                ),
                (
                    "titre_cours",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Cours"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DETECTED", "Détectée"),
                            ("IMPORTING", "Import en cours"),
                            ("APPLIED", "Appliquée"),
                            ("FAILED", "Échouée"),
                            ("IGNORED", "Ignorée"),
                        ],
                        db_index=True,
                        default="DETECTED",
                        max_length=20,
                    ),
                ),
                ("erreur", models.TextField(blank=True, default="")),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="satellite_updates_applied",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "import_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="satellite_updates",
                        to="apprentissage.importjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mise à jour satellite",
                "verbose_name_plural": "Mises à jour satellite",
                "ordering": ["-detected_at"],
            },
        ),
    ]
