# Generated by Django 4.2.30 on 2026-09-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apprentissage", "0013_satelliteupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="cours",
            name="source",
            field=models.CharField(
                choices=[
                    ("MANUEL", "Créé sur la plateforme"),
                    ("IMPORT", "Importé (ZIP)"),
                    ("SATELLITE", "Reçu par satellite"),
                ],
                default="MANUEL",
                help_text="Les cours « satellite » sont remplacés à chaque mise à jour ; les autres (préchargés / créés à la main) sont persistants.",
                max_length=12,
                verbose_name="Origine",
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="source",
            field=models.CharField(
                default="IMPORT",
                help_text="Origine posée sur les cours créés : IMPORT / SATELLITE",
                max_length=12,
            ),
        ),
    ]
