# Generated by Django 4.2.30 on 2026-09-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apprentissage", "0014_cours_source_importjob_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="pdfs_indexes",
            field=models.PositiveIntegerField(
                default=0, help_text="PDF indexés dans ChromaDB"
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="pdfs_total",
            field=models.PositiveIntegerField(default=0, help_text="PDF à indexer"),
        ),
    ]
