# Generated by Django 4.2.30 on 2026-06-16 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apprentissage", "0001_initial"),
        ("tuteur_ia", "0002_sessionqcm"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.JSONField(default=list)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "chapitre",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qcm_cache",
                        to="apprentissage.chapitre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache de questions QCM",
                "verbose_name_plural": "Caches de questions QCM",
            },
        ),
    ]
