# Generated by Django 4.2.30 on 2026-06-18 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("apprentissage", "0006_alter_document_fichier_pdf"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tuteur_ia", "0003_questioncache"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionAssistant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("messages", models.JSONField(default=list)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "chapitre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions_assistant",
                        to="apprentissage.chapitre",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions_assistant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Assistant",
                "verbose_name_plural": "Sessions Assistant",
                "ordering": ["-date_modification"],
            },
        ),
    ]
