# Generated by Django 5.2.15 on 2026-06-27 23:21
#
# NOTE : cette migration est une branche parallèle de
# `0006_graphcheckpoint_graphwrite`. Sur une base neuve, l'autre branche + la
# migration 0007 créent déjà les tables GraphCheckpoint / GraphWrite, renomment
# les index de DocumentChunk et posent les contraintes. Toutes les opérations
# ci-dessous font donc double emploi côté base : on les garde en **état seulement**
# (`SeparateDatabaseAndState` avec `database_operations=[]`) afin que
# `python manage.py migrate` fonctionne sur une base 100 % neuve (tests, CI,
# nouveau nœud hors-ligne) sans casser les bases déjà migrées.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuteur_ia', '0005_documentchunk'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='GraphCheckpoint',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('thread_id', models.CharField(db_index=True, max_length=100)),
                        ('checkpoint_ns', models.CharField(default='', max_length=100)),
                        ('checkpoint_id', models.CharField(max_length=100)),
                        ('parent_checkpoint_id', models.CharField(blank=True, max_length=100, null=True)),
                        ('type', models.CharField(default='json', max_length=50)),
                        ('checkpoint', models.BinaryField()),
                        ('metadata', models.BinaryField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'verbose_name': 'Checkpoint LangGraph',
                        'verbose_name_plural': 'Checkpoints LangGraph',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='GraphWrite',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('thread_id', models.CharField(db_index=True, max_length=100)),
                        ('checkpoint_ns', models.CharField(default='', max_length=100)),
                        ('checkpoint_id', models.CharField(db_index=True, max_length=100)),
                        ('task_id', models.CharField(max_length=100)),
                        ('idx', models.IntegerField()),
                        ('channel', models.CharField(max_length=100)),
                        ('type', models.CharField(max_length=50)),
                        ('value', models.BinaryField()),
                    ],
                    options={
                        'verbose_name': 'Write LangGraph',
                        'verbose_name_plural': 'Writes LangGraph',
                    },
                ),
                # même état final que la migration 0007 (branche parallèle)
                migrations.AlterUniqueTogether(
                    name='graphcheckpoint',
                    unique_together={('thread_id', 'checkpoint_ns', 'checkpoint_id')},
                ),
                migrations.AlterUniqueTogether(
                    name='graphwrite',
                    unique_together={('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx')},
                ),
            ],
        ),
    ]
