# Generated by Django 5.2.15 on 2026-06-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuteur_ia', '0005_documentchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, max_length=100)),
                ('checkpoint_ns', models.CharField(default='', max_length=100)),
                ('checkpoint_id', models.CharField(max_length=100)),
                ('parent_checkpoint_id', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(default='json', max_length=50)),
                ('checkpoint', models.BinaryField()),
                ('metadata', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Checkpoint LangGraph',
                'verbose_name_plural': 'Checkpoints LangGraph',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GraphWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, max_length=100)),
                ('checkpoint_ns', models.CharField(default='', max_length=100)),
                ('checkpoint_id', models.CharField(db_index=True, max_length=100)),
                ('task_id', models.CharField(max_length=100)),
                ('idx', models.IntegerField()),
                ('channel', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('value', models.BinaryField()),
            ],
            options={
                'verbose_name': 'Write LangGraph',
                'verbose_name_plural': 'Writes LangGraph',
            },
        ),
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='tuteur_ia_d_chapitr_456626_idx',
            old_name='tuteur_ia_d_chapitr_idx',
        ),
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='tuteur_ia_d_cours_i_763e32_idx',
            old_name='tuteur_ia_d_cours_id_idx',
        ),
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='tuteur_ia_d_documen_4b4ad5_idx',
            old_name='tuteur_ia_d_documen_idx',
        ),
        migrations.AlterUniqueTogether(
            name='graphcheckpoint',
            unique_together={('thread_id', 'checkpoint_ns', 'checkpoint_id')},
        ),
        migrations.AlterUniqueTogether(
            name='graphwrite',
            unique_together={('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx')},
        ),
    ]
