# Generated by Django 4.2.30 on 2026-06-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tuteur_ia", "0006_graphcheckpoint_graphwrite"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="graphcheckpoint",
            name="unique_graph_checkpoint",
        ),
        migrations.RemoveConstraint(
            model_name="graphwrite",
            name="unique_graph_write",
        ),
        migrations.RenameIndex(
            model_name="documentchunk",
            new_name="tuteur_ia_d_chapitr_456626_idx",
            old_name="tuteur_ia_d_chapitr_idx",
        ),
        migrations.RenameIndex(
            model_name="documentchunk",
            new_name="tuteur_ia_d_cours_i_763e32_idx",
            old_name="tuteur_ia_d_cours_id_idx",
        ),
        migrations.RenameIndex(
            model_name="documentchunk",
            new_name="tuteur_ia_d_documen_4b4ad5_idx",
            old_name="tuteur_ia_d_documen_idx",
        ),
        migrations.AlterUniqueTogether(
            name="graphcheckpoint",
            unique_together={("thread_id", "checkpoint_ns", "checkpoint_id")},
        ),
        migrations.AlterUniqueTogether(
            name="graphwrite",
            unique_together={
                ("thread_id", "checkpoint_ns", "checkpoint_id", "task_id", "idx")
            },
        ),
    ]
