# Generated by Django 5.2.15 on 2026-06-29 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuteur_ia', '0006_graphcheckpoint_graphwrite_and_more'),
        ('tuteur_ia', '0007_remove_graphcheckpoint_unique_graph_checkpoint_and_more'),
    ]

    operations = [
    ]
