# Generated by Django 5.2.15 on 2026-06-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuteur_ia', '0008_merge_20260629_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphcheckpoint',
            name='checkpoint_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='graphcheckpoint',
            name='checkpoint_ns',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='graphcheckpoint',
            name='parent_checkpoint_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='graphcheckpoint',
            name='thread_id',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='graphwrite',
            name='channel',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='graphwrite',
            name='checkpoint_id',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='graphwrite',
            name='checkpoint_ns',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='graphwrite',
            name='task_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='graphwrite',
            name='thread_id',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
