# Generated by Django 4.2.30 on 2026-06-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                verbose_name="Photo de profil",
            ),
        ),
    ]
