# Generated by Django 6.0.4 on 2026-05-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_utilisateur_is_formateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='niveau',
            field=models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé')], default='DEBUTANT', max_length=20),
        ),
    ]
