# Generated by Django 4.2.30 on 2026-06-17 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_utilisateur_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("COMPTE_ACTIVE", "Compte Activé"),
                            ("QCM_CORRIGE", "QCM Corrigé"),
                            ("NOUVEAU_COURS", "Nouveau Cours"),
                            ("DEMANDE_TRAITEE", "Demande Traitée"),
                        ],
                        max_length=20,
                        verbose_name="Type de notification",
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="URL associée",
                    ),
                ),
                ("lu", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-date_creation"],
            },
        ),
    ]
