# Generated by Django 4.2.30 on 2026-06-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="is_temp_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="temp_password_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
