# Generated by Django 4.2.30 on 2026-06-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_utilisateur_is_temp_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("COMPTE_ACTIVE", "Compte Activé"),
                    ("QCM_CORRIGE", "QCM Corrigé"),
                    ("NOUVEAU_COURS", "Nouveau Cours"),
                    ("DEMANDE_TRAITEE", "Demande Traitée"),
                    ("NOUVELLE_INSCRIPTION", "Nouvelle Inscription"),
                ],
                max_length=20,
                verbose_name="Type de notification",
            ),
        ),
    ]
