# Generated by Django 6.0.4 on 2026-06-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_utilisateur_first_name_utilisateur_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('COMPTE_ACTIVE', 'Compte Activé'), ('QCM_CORRIGE', 'QCM Corrigé'), ('NOUVEAU_COURS', 'Nouveau Cours'), ('DEMANDE_TRAITEE', 'Demande Traitée'), ('NOUVELLE_INSCRIPTION', 'Nouvelle Inscription'), ('NOUVELLE_DEMANDE', 'Nouvelle Demande')], max_length=20, verbose_name='Type de notification'),
        ),
    ]
