# Generated by Django 6.0.4 on 2026-06-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
