# Generated by Django 5.2.16 on 2026-08-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_utilisateur_onboarding_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSysteme',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('mode_hors_ligne', models.BooleanField(default=False, help_text="Active le mode déconnecté. Coupe l'envoi d'e-mails et force l'IA locale.", verbose_name='Mode Hors-Ligne')),
                ('llm_provider', models.CharField(choices=[('AUTO', 'Automatique (Groq -> Ollama)'), ('GROQ', 'Forcer Groq (API)'), ('OPENAI', 'Forcer OpenAI (API)'), ('OLLAMA', 'Forcer Ollama (Local)')], default='AUTO', max_length=20, verbose_name='Fournisseur IA (LLM)')),
                ('activer_hls', models.BooleanField(default=True, help_text='Active la génération de vidéos par morceaux avec FFmpeg.', verbose_name='Activer HLS (Projet FLUTE)')),
            ],
            options={
                'verbose_name': 'Configuration Système',
                'verbose_name_plural': 'Configurations Système',
            },
        ),
    ]
