# Generated by Django 4.2.30 on 2026-08-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_configurationsysteme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="Adresse e-mail"
            ),
        ),
    ]
